---
- hosts: virtualbox
  become: yes
  become_method: sudo
  tasks:
    - name: Update and upgrade apt packages
      become: true
      apt:
        upgrade: yes
        update_cache: yes
        cache_valid_time: 86400 #One day

    - name: Install vagrant
      apt:
        deb: https://releases.hashicorp.com/vagrant/2.2.15/vagrant_2.2.15_x86_64.deb

    - name: Add an Apt signing key
      ansible.builtin.apt_key:
        id: B9F8D658297AF3EFC18D5CDFA2F683C52980AECF
        url: https://www.virtualbox.org/download/oracle_vbox_2016.asc
        state: present

    - name: Add virtualbox repository into sources list
      ansible.builtin.apt_repository:
        repo: deb [arch=amd64] https://download.virtualbox.org/virtualbox/debian bionic contrib
        state: present

    - name: Install kubectl
      community.general.snap:
        name:
          - kubectl
        classic: yes

    - name: Add ansible repository
      ansible.builtin.apt_repository:
        repo: ppa:ansible/ansible
        state: present
        
    - name: Install a list of packages
      apt:
        pkg:
        - virtualbox
        - ansible
        - virtualbox-guest-additions-iso
        - dkms
        - apt-transport-https
        - ca-certificates
        - curl
        - python-pip
        state: latest

    - name: Install openshift python package
      pip:
        name: openshift

    - name: Install k8s ansible collection
      shell: ansible-galaxy collection install community.kubernetes

    - name: Install k8s collection dependencies
      shell: ansible-galaxy collection install -r requirements.yml
      
    - name: Install vagrant-vbguest
      shell: vagrant plugin install vagrant-vbguest

    - name: Install vagrant-scp
      shell: vagrant plugin install vagrant-scp

    - name: Reboot VM
      reboot:
        reboot_timeout: 3600
      tags: [restart]