---
- hosts: virtualbox
  become: yes
  become_method: sudo
  tasks:
    - name: Copy k8s configuration files
      copy: src=kubernetes-setup dest=/k8s mode=0770

    - name: Run Vagrant
      shell: vagrant up 
      args:
        chdir: /k8s/kubernetes-setup
      tags: vagrant-init

    - name: Copy systemd service file to server
      shell: cp /k8s/kubernetes-setup/vagrant-autostart.service /etc/systemd/system

    - name: Enable vagrant-autostart service
      ansible.builtin.systemd:
        name: vagrant-autostart
        enabled: yes