---
- hosts: virtualbox
  become: yes
  become_method: sudo
  tasks:
    - name: Reload Vagrant
      shell: vagrant reload 
      args:
        chdir: /k8s/kubernetes-setup
      tags: vagrant-reload

    - name: Create a directory fo kubectl config
      ansible.builtin.file:
        path: ~/.kube/
        state: directory

    - name: Copy kubectl config
      shell: cp /k8s/kubernetes-setup/config ~/.kube/config

    - name: Change file ownership, group and permissions
      ansible.builtin.file:
        path: ~/.kube/config
        owner: root
        group: root
        mode: '0400'

    - name: Copy kafka configuration files
      copy: src=kafka-setup dest=/k8s mode=0770

    - name: Wait for master node
      wait_for:
        host: 127.0.0.1
        port: 6443
        delay: 10
        timeout: 30
      retries: 5
