---
- hosts: virtualbox
  become: yes
  become_method: sudo
  tasks:
    - name: Reload Vagrant
      shell: vagrant reload 
      args:
        chdir: /k8s/kubernetes-setup

    - name: Create a directory fo kubectl config
      ansible.builtin.file:
        path: ~/.kube/
        state: directory

    - name: Copy kubectl config
      shell: cp /k8s/kubernetes-setup/config ~/.kube/config

    - name: Copy kafka configuration files
      copy: src=kafka-setup dest=/k8s mode=0777

    - name: Run kafka deploy
      shell: ansible-playbook main.yml
      args:
        chdir: /k8s/kafka-setup/
      