---
- hosts: virtualbox
  become: yes
  become_method: sudo
  tasks:
    - name: Copy vagrant files
      copy: src=kubernetes-setup dest=/mnt/data mode=0777

    - name: Run Vagrant
      shell: vagrant up 
      args:
        chdir: /mnt/data/kubernetes-setup
      tags: vagrant-init

    - name: Copy systemd service file to server
      copy:
        src: vagrant-autostart.service
        dest: /etc/systemd/system
        owner: root
        group: root

    - name: Enable vagrant-autostart service
      ansible.builtin.systemd:
        name: vagrant-autostart
        enabled: yes