---
- hosts: win
  tasks:
    - name: 
      win_shell: Disable-WindowsOptionalFeature -Online -FeatureName Microsoft-Hyper-V-All
    - name: 
      win_shell: iex ((new-object net.webclient).DownloadString('https://chocolatey.org/install.ps1'))
    - name: 
      win_shell: cinst virtualbox vagrant -y
    - name: 
      win_path:
        elements: C:\HashiCorp\Vagrant\bin\vagrant.exe
