---
- hosts: localhost
  tasks:
    - name: Add repo
      community.kubernetes.helm_repository:
        name: stable
        repo_url: "https://charts.bitnami.com/bitnami"

    - name: Create kafka cluster
      shell: kubectl apply -f ./kafka-cluster.yaml -n kafka
      args:
        chdir: /k8s/kafka-setup

    - name: Wait till deployment will be finished
      shell: kubectl wait kafka/my-cluster --for=condition=Ready --timeout=300s -n kafka 
      args:
        chdir: /k8s/kafka-setup
