---
- hosts: localhost
  tasks:
    - name: Add repo
      community.kubernetes.helm_repository:
        name: stable
        repo_url: "https://charts.bitnami.com/bitnami"

    - name: Deploy Kafka
      community.kubernetes.helm:
        name: kafka
        chart_ref: bitnami/kafka
        release_namespace: kafka
        create_namespace: true
        update_repo_cache: yes
