kind: Service
apiVersion: v1
metadata:
  name: kafka
  namespace: kafka
  labels:
    app: kafka
spec:
  ports:
    - name: internal
      protocol: TCP
      port: 9092
      targetPort: 9092
      nodePort: 30000
  selector:
    app: kafka
  type: NodePort
  sessionAffinity: None